//! Runtime game configuration: compiled-in defaults, overridden by
//! lib/etc/config.
//! Stock ships no lib/etc/config, so these literals are normative; cedit
//! (stage 9) writes the file and load_config reads it back.

pub type BStr = Vec<u8>;

#[derive(Debug, Clone)]
pub struct Config {
    // Game play options.
    pub script_players: bool,
    /// pk_setting: 0 = OFF, 1 = LIMITED (PLR_KILLER flagging),
    /// 2 = FREEFORALL.
    pub pk_setting: i32,
    /// pt_setting: 0 = OFF, 1 = LIMITED (PLR_THIEF
    /// flagging), 2 = FREEFORALL.
    pub pt_setting: i32,
    pub level_can_shout: i32,
    pub holler_move_cost: i32,
    pub tunnel_size: i32,
    pub max_exp_gain: i32,
    pub max_exp_loss: i32,
    pub max_npc_corpse_time: i32,
    pub max_pc_corpse_time: i32,
    pub idle_void: i32,
    pub idle_rent_time: i32,
    pub idle_max_level: i32,
    pub dts_are_dumps: bool,
    pub load_into_inventory: bool,
    pub ok: BStr,
    pub huh: BStr,
    pub noperson: BStr,
    pub noeffect: BStr,
    pub track_through_doors: bool,
    pub no_mort_to_immort: bool,
    pub diagonal_dirs: bool,

    // Rent/crash.
    pub free_rent: bool,
    pub max_obj_save: i32,
    pub min_rent_cost: i32,
    pub auto_save: bool,
    pub autosave_time: i32,
    pub crash_file_timeout: i32,
    pub rent_file_timeout: i32,
    pub auto_pwipe: bool,
    pub selfdelete_fastwipe: bool,

    // Rooms.
    pub mortal_start_room: i32,
    pub immort_start_room: i32,
    pub frozen_start_room: i32,
    pub donation_room_1: i32,
    pub donation_room_2: i32,
    pub donation_room_3: i32,

    // Operation.
    pub dflt_port: u16,
    pub dflt_ip: Option<BStr>,
    pub dflt_dir: BStr,
    pub logname: Option<BStr>,
    pub max_playing: i32,
    pub max_filesize: i32,
    pub max_bad_pws: i32,
    pub siteok_everyone: bool,
    pub nameserver_is_slow: bool,
    pub auto_save_olc: bool,
    pub use_new_socials: bool,
    pub menu: BStr,
    pub welc_messg: BStr,
    pub start_messg: BStr,
    pub use_autowiz: bool,
    pub min_wizlist_lev: i32,
    pub display_closed_doors: bool,
    pub map_option: i32,
    pub default_map_size: i32,
    pub default_minimap_size: i32,
    pub medit_advanced_stats: bool,
    pub ibt_autosave: bool,
    pub protocol_negotiation: bool,
    pub special_in_comm: bool,
    pub debug_mode: i32,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            script_players: false,
            pk_setting: 0,
            pt_setting: 0,
            level_can_shout: 1,
            holler_move_cost: 20,
            tunnel_size: 2,
            max_exp_gain: 100000,
            max_exp_loss: 500000,
            max_npc_corpse_time: 5,
            max_pc_corpse_time: 10,
            idle_void: 8,
            idle_rent_time: 48,
            idle_max_level: mud_data::types::LVL_IMMORT as i32,
            dts_are_dumps: true,
            load_into_inventory: true,
            ok: b"Okay.\r\n".to_vec(),
            huh: b"Huh!?!\r\n".to_vec(),
            noperson: b"No one by that name here.\r\n".to_vec(),
            noeffect: b"Nothing seems to happen.\r\n".to_vec(),
            track_through_doors: true,
            no_mort_to_immort: true,
            diagonal_dirs: false,
            free_rent: true,
            max_obj_save: 30,
            min_rent_cost: 100,
            auto_save: true,
            autosave_time: 5,
            crash_file_timeout: 10,
            rent_file_timeout: 30,
            auto_pwipe: false,
            selfdelete_fastwipe: true,
            mortal_start_room: 3001,
            immort_start_room: 1204,
            frozen_start_room: 1202,
            donation_room_1: 3063,
            donation_room_2: 5510,
            donation_room_3: 235,
            dflt_port: 4000,
            dflt_ip: None,
            dflt_dir: b"lib".to_vec(),
            logname: None,
            max_playing: 300,
            max_filesize: 50000,
            max_bad_pws: 3,
            siteok_everyone: true,
            nameserver_is_slow: false,
            auto_save_olc: true,
            use_new_socials: true,
            menu: b"\r\nWelcome to RustMUD!\r\n\t(0\t)) Exit from RustMUD.\r\n\t(1\t)) Enter the game.\r\n\t(2\t)) Enter description.\r\n\t(3\t)) Read the background story.\r\n\t(4\t)) Change password.\r\n\t(5\t)) Delete this character.\r\n\r\n   Make your choice: ".to_vec(),
            welc_messg: b"\r\nWelcome to RustMUD!  May your visit here be... Enlightening\r\n\r\n".to_vec(),
            start_messg: b"Welcome.  This is your new RustMUD character!  You can now earn gold,\r\ngain experience, find weapons and equipment, and much more -- while\r\nmeeting people from around the world!\r\n".to_vec(),
            use_autowiz: true,
            min_wizlist_lev: mud_data::types::LVL_GOD as i32,
            display_closed_doors: true,
            map_option: 2, // MAP_IMM_ONLY
            default_map_size: 6,
            default_minimap_size: 2,
            medit_advanced_stats: true,
            ibt_autosave: true,
            protocol_negotiation: true,
            special_in_comm: true,
            debug_mode: 0,
        }
    }
}
